- set_fact: with_stop="{{ instance.with_stop | default(lxc_backup_with_stop)}}"
- set_fact: warning_options="{{ '--warning=no-file-ignored' if with_stop else '--warning=no-file-removed --warning=no-file-changed --warning=no-file-ignored' }}"

- block:
  - name: Stop container - {{ instance.name }}
    command: lxc-stop --name {{ instance.name }}

  - name: Wait {{ lxc_backup_wait_seconds }} to continue - {{ instance.name }}
    pause:
      seconds: '{{ lxc_backup_wait_seconds }}'

  when: with_stop

- name: Ensures mount point exists - {{ instance.name }}
  file:
    path: '{{ lxc_backup_mount_parent_dir }}/{{ instance.name }}'
    state: directory

- name: Mount lxc container - {{ instance.name }}
  mount:
    name: '{{ lxc_backup_mount_parent_dir }}/{{ instance.name }}'
    src: /dev/{{ lxc_backup_vg_name }}/{{ instance.name }}
    fstype: '{{ lxc_backup_mount_fstype }}'
    opts: '{{ lxc_backup_mount_opts }}'
    state: mounted

- name: Create backup - {{ instance.name }}
  command: "tar --numeric-owner {{ warning_options }} -czf {{ lxc_backup_dir }}/lxc-{{ instance.name }}-{{ date_stamp }}.tar.gz {{ instance.name }}"
  args:
    chdir: '{{ lxc_backup_mount_parent_dir }}'

- name: Unmount lxc container - {{ instance.name }}
  mount:
    name: '{{ lxc_backup_mount_parent_dir }}/{{ instance.name }}'
    state: unmounted

- name: Start container - {{ instance.name }}
  command: lxc-start --name {{ instance.name }}
  when: with_stop
